# Generated by Django 3.0.3 on 2020-04-03 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0005_auto_20200403_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('alamat', models.TextField(default=None)),
                ('tanggal_lahir', models.DateField(default=None)),
                ('umur', models.IntegerField(default=None)),
                ('jenis_kelamin', models.CharField(default=None, max_length=10)),
                ('nilai_un_matematika', models.IntegerField(default=None)),
                ('nilai_un_indonesia', models.IntegerField(default=None)),
                ('nilai_un_inggris', models.IntegerField(default=None)),
            ],
        ),
    ]
