# Generated by Django 3.0.3 on 2020-04-03 23:34

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0007_auto_20200404_0558'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='siswa',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='siswa',
            name='alamat',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='jenis_kelamin',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nilai_un_indonesia',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nilai_un_inggris',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nilai_un_matematika',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nis',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='tanggal_lahir',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='umur',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
