# Generated by Django 3.0.3 on 2020-04-03 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0008_auto_20200404_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='jenis_kelamin',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='nilai_un_indonesia',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='nilai_un_inggris',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='nilai_un_matematika',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='tanggal_lahir',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='umur',
        ),
    ]
