# Generated by Django 3.0.3 on 2020-04-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0009_auto_20200404_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='alamat',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='jenis_kelamin',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='nilai_un_indonesia',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='nilai_un_inggris',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='nilai_un_matematika',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='tanggal_lahir',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='siswa',
            name='umur',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
