# Generated by Django 3.0.3 on 2020-04-04 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0010_auto_20200404_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='siswa', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
