# Generated by Django 3.0.3 on 2020-04-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0012_auto_20200416_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='foto_akta',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='foto_diri',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='foto_ijazah',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
