# Generated by Django 3.0.3 on 2020-04-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0015_auto_20200425_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='tempat_lahir',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
