# Generated by Django 3.0.3 on 2020-04-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0016_siswa_tempat_lahir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='berkas_akta',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='berkas_ijazah',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='berkas_kesehatan',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='foto_diri',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
