# Generated by Django 3.0.3 on 2020-05-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0017_auto_20200428_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='status',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nilai_indonesia',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nilai_inggris',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nilai_ipa',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nilai_matematika',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=5, null=True),
        ),
    ]
