# Generated by Django 3.0.3 on 2020-05-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0020_auto_20200502_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='nilai_indonesia',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nilai_inggris',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nilai_ipa',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nilai_matematika',
            field=models.FloatField(default=None, null=True),
        ),
    ]
