# Generated by Django 3.0.3 on 2020-05-07 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0023_list_events'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='list_events',
            table='tabel_events',
        ),
    ]
