# Generated by Django 3.0.3 on 2020-05-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0024_auto_20200507_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_events',
            name='end_date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='list_events',
            name='start_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
