# Generated by Django 3.0.3 on 2020-05-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0026_auto_20200507_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_events',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='list_events',
            name='start_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
