# Generated by Django 3.0.3 on 2020-05-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0027_auto_20200507_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='list_notifikasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifikasi', models.CharField(max_length=255)),
                ('tanggal_kirim', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
