# Generated by Django 3.0.3 on 2020-05-25 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0028_list_notifikasi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list_notifikasi',
            options={'ordering': ['-tanggal_kirim']},
        ),
        migrations.AddField(
            model_name='list_notifikasi',
            name='siswa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to='page_siswa.Siswa'),
        ),
        migrations.AlterModelTable(
            name='list_notifikasi',
            table='tabel_notifikasi',
        ),
    ]
