# Generated by Django 3.0.3 on 2020-05-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0029_auto_20200525_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list_notifikasi',
            options={'ordering': ['-tanggal_notifikasi']},
        ),
        migrations.AlterModelOptions(
            name='siswa',
            options={'ordering': ['nis']},
        ),
        migrations.RenameField(
            model_name='list_notifikasi',
            old_name='tanggal_kirim',
            new_name='tanggal_notifikasi',
        ),
    ]
