# Generated by Django 3.0.3 on 2020-06-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0031_auto_20200609_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='sekolah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default=None, max_length=255)),
                ('alamat', models.TextField()),
                ('kuota_siswa', models.PositiveIntegerField(default=0)),
                ('status_pendaftaran', models.IntegerField(choices=[(0, 'Pendaftaran di Buka'), (1, 'Pendaftaran di Tutup')], default=0)),
            ],
            options={
                'db_table': 'tabel_sekolah',
            },
        ),
        migrations.AlterField(
            model_name='siswa',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pelengkapan Identias Diri'), (1, 'Pelengkapan Berkas-Berkas'), (2, 'Pengajuan Pendaftaran'), (3, 'Sedang Diverifikasi'), (4, 'Verifikasi Gagal'), (5, 'Proses Daftar Ulang'), (6, 'Proses Seleksi Siswa'), (7, 'Tidak Diterima'), (8, 'Diterima'), (9, 'Pendaftaran ditutup'), (10, 'Jalur Zonasi'), (11, 'Jalur Afirmasi'), (12, 'Jalur Perpindahan'), (13, 'Jalur Prestasi')], default=0, null=True),
        ),
    ]
