# Generated by Django 3.0.3 on 2020-06-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0033_auto_20200610_0257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sekolah',
            old_name='kuota_siswa',
            new_name='daya_tampung',
        ),
        migrations.AddField(
            model_name='siswa',
            name='berkas_tambahan',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
    ]
