# Generated by Django 3.0.3 on 2020-06-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0036_auto_20200611_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sekolah',
            name='alamat',
            field=models.TextField(default=None),
        ),
    ]
