# Generated by Django 3.0.3 on 2020-06-15 23:53

from django.db import migrations, models
import page_siswa.models


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0037_auto_20200613_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='sekolah',
            name='sisa_afirmasi',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sekolah',
            name='sisa_perpindahan',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sekolah',
            name='sisa_prestasi',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sekolah',
            name='sisa_zonasi',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='berkas_akta',
            field=models.ImageField(default=None, null=True, upload_to=page_siswa.models.akta_image_path),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='berkas_ijazah',
            field=models.ImageField(default=None, null=True, upload_to=page_siswa.models.ijazah_image_path),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='berkas_kesehatan',
            field=models.ImageField(default=None, null=True, upload_to=page_siswa.models.kesehatan_image_path),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='berkas_tambahan',
            field=models.ImageField(default=None, null=True, upload_to=page_siswa.models.tambahan_image_path),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='foto_diri',
            field=models.ImageField(default=None, null=True, upload_to=page_siswa.models.foto_image_path),
        ),
    ]
