# Generated by Django 3.0.3 on 2020-06-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0038_auto_20200615_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sekolah',
            name='status_pendaftaran',
            field=models.BooleanField(choices=[(0, 'Pendaftaran dibuka'), (1, 'Pendaftaran ditutup')], default=0),
        ),
    ]
