# Generated by Django 3.0.3 on 2020-07-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0039_auto_20200616_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_notifikasi',
            name='tanggal_notifikasi',
            field=models.DateField(auto_now=True),
        ),
    ]
