# Generated by Django 3.0.3 on 2020-07-28 03:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0040_auto_20200712_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list_notifikasi',
            options={'ordering': ['-tanggal_notifikasi', '-id']},
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nilai_matematika',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator('0.01'), django.core.validators.MaxValueValidator('100')]),
        ),
    ]
