# Generated by Django 3.0.3 on 2020-07-28 03:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0041_auto_20200728_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='nilai_matematika',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
