# Generated by Django 3.0.3 on 2020-07-28 06:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0042_auto_20200728_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siswa',
            name='nilai_indonesia',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nilai_inggris',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='siswa',
            name='nilai_ipa',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
