# Generated by Django 3.0.3 on 2020-07-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0043_auto_20200728_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='sekolah',
            name='jam_daftar_ulang',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='sekolah',
            name='tanggal_daftar_ulang',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='sekolah',
            name='status_pendaftaran',
            field=models.IntegerField(choices=[(0, 'Pendaftaran dibuka'), (1, 'Pendaftaran ditutup'), (2, 'Proses Seleksi'), (3, 'Proses Daftar Ulang'), (4, 'Pengumuman')], default=1),
        ),
    ]
