# Generated by Django 3.0.3 on 2020-07-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0044_auto_20200729_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sekolah',
            name='jam_daftar_ulang',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='sekolah',
            name='tanggal_daftar_ulang',
            field=models.TextField(default=None, null=True),
        ),
    ]
