# Generated by Django 3.0.3 on 2020-07-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0046_auto_20200729_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sekolah',
            name='alamat_lengkap',
            field=models.TextField(default=None, null=True),
        ),
    ]
