# Generated by Django 3.0.3 on 2020-07-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_siswa', '0047_auto_20200729_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siswa',
            old_name='asal_sekolah',
            new_name='jalur_pendaftaran',
        ),
    ]
